### ISSUE TITLE
Move new files in place: Could not rename ...

### ISSUE THREAD

**Issue by STaRDoGG** [nextcloud/updater#276]
The last 2 times I've used the updater I've been getting stuck here:

![image](https://user-images.githubusercontent.com/1524526/77589431-a71e3000-6eb9-11ea-988a-2eba40b41bf2.png)

I have to manually click the "Retry" button like 16 million times and it completes, apparently fine, and checking the version when it's done shows it's the latest version. Any solution to this?

I'm using the containerized version:

```
   nextcloud:
        # https://hub.docker.com/r/linuxserver/nextcloud
        image: linuxserver/nextcloud:latest
        container_name: nextcloud
        hostname: nextcloud
        environment:
          - TZ='America/Chicago'
        volumes:
          - "scotts_nextcloud:/config" # Nextcloud Configs
          - "/i/Nextcloud:/data"       # Storage area
        restart: unless-stopped
        networks:
          - ocs
          - odb
```
