### ISSUE TITLE
Error "Move new files in place" during update when Data and WWW folder are on different drives

### ISSUE THREAD

**Issue by t3nk3y** [nextcloud/updater#457]
**Problem**
I consistently have a failure during update when running inside docker, when my data directory is on a different drive(mount/volume) than my WWW directory.

**Versions**
This is most recently occurring when upgrading from 24.0.7 to 24.0.8.  However, I've had this happen on every version since I moved my application directories to a different drive than the data paths.
While I am doing this from the Web upgrader, the same issues occurs from the command line updater.

**More Detail**
This used to not be a problem for me, as I was using only external storage for data, but there is a whole slew of features that don't work if you don't use the data paths that are inside of("local to") Nextcloud.

I do, however, come offering an explanation(partial) for the issue, and a potential code solution(will do a PR if I must, but would prefer if devs could examine the simple code example below).

I believe the issue is that when attempting to use the rename command to do a move, PHP is assuming the files are on the same drive, and attempting an actual rename operation, as opposed to a move operation.  I'd assume it's designed to deal with selecting the appropriate move method, however, within the docker environment, it might be getting confused as to if the two paths are on the same volume or not.

Further more, this may be related to the configuration of my data and or application drive.  Both are using BTRFS, and the data drive is sitting behind a cache drive, and pooled with other data drives, using Merger.fs  The point being, the setup is unique enough that it would make some sense that detecting the filesystem boundary properly might be an issue.

**Solutions:**

1. Provide proper support for placing the Data path and the rest of the application in different locations.  There are other tickets discussing this concept, and it makes perfect sense from an environment design to expect data to be on slower storage volumes and applications files to be on high speed storage.  In this case, the upgrader could, for instance, download the update to the application drive, instead of to the storage drive.  This would allow for a proper download, extract, rename.  The current assumptions being made by the updater are a cause for this issue.

2. Modify the updater to detect if the source(downloaded/extracted) location is on the same filesystem as the www path the files are being moved to.  If not, then do a copy, and unlink, instead of a rename.

3. Do the workaround I'm doing.  I don't entirely understand why this works, though.  It turns out that when the rename attempt occurs, despite the fact that the rename operation is returning an error, something is figuring out the process, and copying the file to the correct location, anyway, successfully.  Maybe the php rename operation detects the rename failure, and does a copy instead, but return an error?  Anyway it goes, in my specific case, simply, ignoring these error, results in everything working without a problem.  My workaround is to modify the updater code to check if the target file got created, and only throw an error if it didn't.  See below code for the original and changed code to Index.php in the updater path:
```php
		$state = rename($path, $this->baseDir  . '/../' . $fileName);
		if($state === false) {
                    throw new \Exception(
                       	sprintf(
                           'Could not rename %s to %s',
                           $path,
                           $this->baseDir . '/../' . $fileName
                       	)
                    );
		}
```
```php
		$state = rename($path, $this->baseDir  . '/../' . $fileName);
		if($state === false) {
		    //Check if the destination file exists, and only throw an error if it doesn't
                    if(!file_exists($this->baseDir  . '/../' . $fileName)) {**
                    	throw new \Exception(
                        	sprintf(
                            		'Could not rename %s to %s',
	                            	$path,
        	                    	$this->baseDir . '/../' . $fileName
                        	)
                    	);
                    }
		}
```

**Comment by t3nk3y** [comment]
Of course I came up with another workaround via Docker after having thought through this like 3 times now over the course of the last 3 updates.

Mapping a volume(from the application drive) to the path that the update will be extracted to, also solves this problem, and does so without anything performing a copy and delete.  It's a bit tricky though, as the Nextcloud instance gets (what I assume as a randomly generated ID) when it's created, so you need to get your instance ID to map the proper drives.  In my case, I already has this as I was mapping the appdata directory(which annoyingly sits inside the data directory) to the high speed drive, which is what started the problem.

For reference, for anyone running Nextcloud via Linuxserver.io in Docker using Compose, through Portainer, not in a swarm mode.  Here is a cleaned version of my docker-compose that works in this scenario.
**Be sure to replace oc8Inst2Id05 with your instance ID.  You should find an appdata_oc8Inst2Id05 (with your instance ID, not this string, in your data folder) and can get the ID from that.**
```yaml
version: '3.8'

volumes:
  app:
  db:
  db2:
  redis:
    driver: local

services:
  app:
    image: linuxserver/nextcloud:latest

    restart: always
    depends_on:
      - db
      - redis
      - imaginary
    ports:
      - 443:443
    environment:
      - PUID=33
      - PGID=33
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - '/dev:/dev'
      - /mnt/appdata/nextcloud/config:/config
      - /mnt/storage:/mnt/storage
      - /mnt/appdata/nextcloud/appdata:/mnt/storage/nextcloud/data/appdata_oc8Inst2Id05
      - /mnt/appdata/nextcloud/updater:/mnt/storage/nextcloud/data/updater-oc8Inst2Id05

  db:
    image: mariadb
    restart: always
    command: >
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-file-per-table=1
      --skip-innodb-read-only-compressed
      --innodb-buffer-pool-size=4G
      --innodb-log-file-size=64G
      --max-allowed-packet=128M
      --key-buffer-size=10M

    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - redis:/var/lib/redis

  imaginary:
    image: ghcr.io/italypaleale/imaginary:master
    restart: always
    command: -enable-url-source

```
